#!/bin/sh

# Oringal code from justin parrott at 2600.

NUMTHREADS=10
TIMEOUT=3
STARTPORT=1
STOPPORT=1024

usage()  {
          echo "usage: $0 [options] host"
          echo " -s startport     What port to START with."
          echo " -S stopport      What port to STOP with."
          echo " -t numthreads    Number pocesses to execute in parallel."
          echo " -w timeout       Timeout value."
          exit 1
}

while getopts s:S:t:w: opt
do
          case $opt in
          s)        STARTPORT="$OPTARG";;
          S)        STOPPORT="$OPTARG";;
          t)        NUMTHREADS="$OPTARG";;
          w)        TIMEOUT="$OPTARG";;
          \?)       usage;;
          esac
done
shift $((OPTIND - 1))

if [ $# -ne 1 ]
then
          usage
fi
HOST="$1"

tcping()
{
          nc -z -w "$to" "$host" "$port"
}

i="$STARTPORT"
running_threads=0
while [ "$i" -le "$STOPPORT" ]
do
          port="$i" host="$host" to="$TIMEOUT" tcping &
          running_threads=$((running_threads + 1))
          i=$((i+1))
          
          if [ $running_threads -eq "$NUMTHREADS" ]
          then
                    wait
                    running_threads=0
          fi
done

wait
